export const DAYS = 'days'
export const DAY = 'day'
export const MONTHS = 'months'
export const HOUR = 'hour'
export const HOURS = 'hours'
export const MINUTE = 'minute'

export const DATE_FORMATE = 'dd/mm/yyyy'
export const TIME_FORMATE = 'hh:mm A'
export const DATE_TIME_FORMATE = 'DD MMM YYYY hh:mm:ss'